apiVersion: v1
kind: Pod
metadata:
 name: my-nginx
 labels:
  app: nginx
  rel: stable
spec:
 containers:
 - name: my-nginx
   image: nginx:alpine
   livenessProbe:
    httpGet:
     path: /index.html
     port: 80
    initialDelaySeconds: 15
    timeoutSeconds: 2
    periodSeconds: 5
    failureThreshold: 1
   readinessProbe:
    httpGet:
     path: /index.html
     port: 80
    initialDelaySeconds: 3
    periodSeconds: 5
    failureThreshold: 1
   ports:
   - containerPort: 80
   resources:



#kubectl create -f nginx.pod.yml --save-config
#kubectl describe pod [pod-name]
#kubectl apply -f nginx.o.yml
#kubectl exec [pod-name] -lt sh
#kubectl edit -f nginx.pod.yml